# Generated by Django 6.0.6 on 2026-07-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyberDeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_alias', models.CharField(max_length=120, verbose_name='Net Alias')),
                ('firmware_hash', models.CharField(max_length=64, unique=True, verbose_name='Firmware Hash')),
                ('glitch_log', models.TextField(blank=True, verbose_name='Glitch Log')),
                ('neon_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Neon Price')),
                ('ram_nodes', models.PositiveIntegerField(default=16, verbose_name='RAM Nodes')),
                ('ice_breaker_level', models.IntegerField(default=1, verbose_name='ICE Breaker Level')),
                ('is_encrypted', models.BooleanField(default=True, verbose_name='Is Encrypted')),
                ('breach_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Breach Timestamp')),
            ],
            options={
                'verbose_name': 'Cyber Deck',
                'verbose_name_plural': 'Cyber Decks',
                'ordering': ['-breach_timestamp'],
            },
        ),
    ]
